### ISSUE TITLE
Windows 11 setup in Getting started?

### ISSUE THREAD

**Issue by timbze** [AndBible/docs#2]
@bvahedy @agrogers I think the Windows 11 section should probably be under the "Getting Started" section, what do you think?

**Comment by bvahedy** [comment]
Yes, I agree it could be placed under a better category. let me know what you guys prefer.

**Comment by agrogers** [comment]
Sure, i agree with you. I think Getting Started > Installation > Windows
11.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by bvahedy** [comment]
Ok, I've moved the instruction to the getting started section.

**Comment by timbze** [comment]
Thank you Ben
