### ISSUE TITLE
Add link to the docs page in this repo

### ISSUE THREAD

**Issue by gelafin** [AndBible/docs#4]
It would be convenient to have a link to https://readthedocs.org/projects/andbible/ in the repo's About section and/or readme

**Comment by agrogers** [comment]
Thanks for the suggestion. I have added it to here:
https://github.com/AndBible/docs

I didnt realise that file was showing up there. I had added it just for
internal reference. It probably should be tidied up a bit.

___________________________
*www.TenOutOfTen.org* <https://www.TenOutOfTen.org>
***@***.***
(+61) 0477 174 193 (Australia)
(+95) 09 250018669 (Myanmar)

**Comment by gelafin** [comment]
Yay, thanks!

Sometimes it's the little things
