### ISSUE TITLE
Wiki: and-bible repo branch

### ISSUE THREAD

**Issue by timbze** [AndBible/docs#5]
@gelafin 

The main and-bible repo now uses `develop` branch for new features etc (especially when new strings are needed), and `current-stable` for bugfixes or other minor improvements

![image](https://user-images.githubusercontent.com/35117769/164310074-c0801c14-24c1-4234-aa29-dd813e44f57f.png)

**Comment by gelafin** [comment]
@timbze Ok, thanks! Updated: https://github.com/AndBible/docs/wiki/Developer-documentation#contributing-code

**Comment by timbze** [comment]
@gelafin thank you, updated main wiki now
